services:
  administracion_api:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: administraciondb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=abc123*+
    restart: always
    ports:
      - "1434:1433"
    volumes:
      - mssql_data:/var/opt/mssql
  distributedcache:
    image: redis
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"
volumes:
  mssql_data: